CREATE TABLE SingedUser(
	uid 		BIGINT 		PRIMARY KEY AUTO_INCREMENT,
	userId 	    VARCHAR(12) NOT NULL, 
	passwd		VARCHAR(16)	NOT NULL,
	userName    VARCHAR(16)	NOT NULL,
	ssn			VARCHAR(20) NOT NULL,
	email       VARCHAR(30)	NOT NULL,
	addr		VARCHAR(30)	NOT NULL,	
	regDate		TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP
	
)AUTO_INCREMENT = 1;

SELECT * FROM SingedUser;