CREATE TABLE Customer(
	cid		BIGINT			PRIMARY KEY AUTO_INCREMENT,
	name	VARCHAR(10)		NOT NULL,
	ssn		CHAR(14)		NOT NULL,
	regDate	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;



CREATE TABLE Account(
	aid			BIGINT		PRIMARY KEY AUTO_INCREMENT,
	accountType CHAR(1)		NOT NULL DEFAULT  'S',
	balance		DOUBLE		NOT NULL DEFAULT 0.0,
	interesRATE DOUBLE		NOT NULL DEFAULT 0.0,
	overdraft	DOUBLE		NOT NULL DEFAULT 0.0,	
	customerId	BIGINT		NOT NULL,	
	regDate		TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP
	CONSTRAINT Account_customerId_FK FOREIGN KEY (customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 3001;










